#version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: bank_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: banking_db
      MYSQL_USER: bank_user
      MYSQL_PASSWORD: bank_pass
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/database.sql:/docker-entrypoint-initdb.d/database.sql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      timeout: 5s
      retries: 10

  payara:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: bank_payara
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:8080"
      - "4848:4848"

volumes:
  mysql_data:
